### ISSUE TITLE
Опций группы юнитов

### ISSUE THREAD

**Issue by IlyaDonskikh** [IlyaDonskikh/property_client#27]
При переходе из АПИ:
```
Processing by Api::V1::PropertyOwnerPanel::PropertyUnitGroupUnitsController#index as HTML
ActionController::RoutingError (No route matches [GET] "/api/v1/property_owner_panel/properties/1/unit_groups/1/contract_options"):
  Parameters: {"back_url"=>"/property_owner_panel/properties/1?back_url=%2Fproperty_owner_panel%2Fproperties", "property_id"=>"1", "unit_group_id"=>"1"}
  
actionpack (5.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
```

При создании опции:
```
Started POST "/api/v1/property_owner_panel/properties/1/unit_groups/1/contract_options" for ::1 at 2019-05-30 00:44:47 +0300
  
ActionController::RoutingError (No route matches [POST] "/api/v1/property_owner_panel/properties/1/unit_groups/1/contract_options"):
```

**Comment by IlyaDonskikh** [comment]
Работает. Тестировал на старой версии АПИ. Закрываю.
